# Numpy Array



In [ ]:
my_list =[1, 2, 3]

In [2]:
import numpy as np

In [3]:
arr = np.array(my_list)

In [4]:
arr

array([1, 2, 3])

In [5]:
my_mat = [[1,2,3], [4,5,6], [7,8,9]] #one dimentional

In [6]:
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
my_mat = [[1,2,3], [4,5,6], [7,8,9]]

In [8]:
np.array(my_mat) #two dimentional

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [11]:
np.arange(0,11,5)

array([ 0,  5, 10])

In [12]:
np.zeros(3)

array([0., 0., 0.])

In [13]:
np.zeros([5,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
np.zeros([5,5,5])

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [16]:
np.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
np.zeros([2,3,2])

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [19]:
np.ones(4)

array([1., 1., 1., 1.])

In [21]:
np.ones([2,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [26]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [28]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [29]:
np.linspace(0,5,100) #one dimentional array

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [30]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [31]:
np.random.rand(5)

array([0.57028   , 0.16707143, 0.19694776, 0.15935734, 0.63644556])

In [32]:
np.random.rand(5,5)

array([[0.4591526 , 0.89830173, 0.03624163, 0.16425835, 0.0106339 ],
       [0.78254354, 0.10773886, 0.87571051, 0.48053329, 0.56962533],
       [0.94038748, 0.00221429, 0.80085778, 0.18263   , 0.28957288],
       [0.07972813, 0.67025334, 0.21942423, 0.85638456, 0.85776307],
       [0.08128207, 0.39983891, 0.46972747, 0.04299063, 0.16491347]])

In [34]:
np.random.randn(2)

array([-0.65915138, -0.85870138])

In [35]:
np.random.randn(5,5)

array([[-0.30140909, -1.44235183,  1.58914784, -0.44679394,  1.12748516],
       [ 1.33433546, -0.11790934, -1.366365  , -0.77837087,  1.40707956],
       [-0.83697208,  0.68243162, -0.49127149, -1.04005389, -0.91177316],
       [ 1.56057265, -0.76369564, -0.81977492,  0.57451927, -0.63078209],
       [ 0.01463253, -0.37829547, -1.53191891, -1.87121576,  1.13606412]])

In [36]:
np.random.randint(5)

2

In [37]:
np.random.randint(1,100)

13

In [38]:
np.random.randint(1,100,10)

array([41, 20, 66, 11, 62, 89, 40, 92, 79,  1])

In [39]:
arr = np.arange(25)

In [40]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [41]:
ranarr = np.random.randint(0,50,10)

In [42]:
ranarr

array([ 7, 27, 10, 45,  3, 45, 39, 13, 41, 10])

In [43]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [44]:
ranarr

array([ 7, 27, 10, 45,  3, 45, 39, 13, 41, 10])

In [45]:
ranarr.max()

45

In [46]:
ranarr.min()

3

In [47]:
ranarr.argmax() #location of max value

3

In [48]:
ranarr.argmin()

4

In [49]:
arr.shape

(25,)

In [50]:
arr = arr.reshape(5,5)

In [51]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [52]:
arr.reshape

<function ndarray.reshape>

In [53]:
arr.shape

(5, 5)

In [54]:
arr.dtype

dtype('int64')

In [55]:
from numpy.random import randint

In [56]:
randint(2,10)

7

# Numpy Indexing & Selection

In [58]:
import numpy as np

In [63]:
arr = np.arange(0,11)

In [64]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [65]:
arr[8]

8

In [66]:
arr[1:5]

array([1, 2, 3, 4])

In [67]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [68]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [69]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [70]:
arr[2:5]

array([2, 3, 4])

In [71]:
arr[0:5] = 100

In [72]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [73]:
arr = np.arange(0,11)

In [74]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [75]:
slice_of_arr = arr[0:6]

In [76]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [77]:
arr[0:6]

array([0, 1, 2, 3, 4, 5])

In [81]:
slice_of_arr[:] = 99

In [82]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [83]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [84]:
arr_copy = arr.copy()

In [85]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [86]:
arr_copy[:] = 100

In [87]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [88]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

# 2D array (matrix)

In [89]:
import numpy as np

In [90]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [91]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [92]:
arr = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [96]:
arr_2d[1][2]

30

In [97]:
arr_2d[2][1]

40

In [98]:
arr_2d[2][2]

45

In [99]:
arr_2d[2,1]

40

In [100]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [101]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [108]:
arr_2d[:2,2:]

array([[15],
       [30]])

In [109]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [112]:
arr_2d[1:,2]

array([30, 45])

## Conditional selection

In [113]:
arr = np.arange(1,11)    #bracket sign is different

In [114]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [116]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [117]:
bool_arr = arr > 5

In [118]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [120]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [121]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [122]:
arr[arr<3]

array([1, 2])

In [123]:
arr_2d = np.arange(50).reshape(5,10)

In [124]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [131]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

## Numpy Operation

In [133]:
import numpy as np

In [134]:
arr = np.arange(0,10)

In [135]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [136]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [137]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [138]:
arr  * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [139]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [140]:
arr - 1

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [141]:
arr / 100

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09])

In [144]:
arr = np.eye(4)

In [145]:
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [146]:
arr * 5

array([[5., 0., 0., 0.],
       [0., 5., 0., 0.],
       [0., 0., 5., 0.],
       [0., 0., 0., 5.]])

In [147]:
arr + arr

array([[2., 0., 0., 0.],
       [0., 2., 0., 0.],
       [0., 0., 2., 0.],
       [0., 0., 0., 2.]])

In [148]:
arr / arr

/var/folders/7g/3l3vrvmn4qn6_tgpd8pkh8_w0000gn/T/ipykernel_10076/3001117470.py:1: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([[ 1., nan, nan, nan],
       [nan,  1., nan, nan],
       [nan, nan,  1., nan],
       [nan, nan, nan,  1.]])

In [149]:
1 / arr

/var/folders/7g/3l3vrvmn4qn6_tgpd8pkh8_w0000gn/T/ipykernel_10076/1528351372.py:1: RuntimeWarning: divide by zero encountered in divide
  1 / arr


array([[ 1., inf, inf, inf],
       [inf,  1., inf, inf],
       [inf, inf,  1., inf],
       [inf, inf, inf,  1.]])

In [150]:
arr ** arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [151]:
arr ** 4

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [153]:
(arr * 3) ** 2

array([[9., 0., 0., 0.],
       [0., 9., 0., 0.],
       [0., 0., 9., 0.],
       [0., 0., 0., 9.]])

In [154]:
np.sqrt(arr)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [155]:
arr = np.arange(1,11)

In [156]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [157]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [158]:
np.max(arr)

10

In [159]:
np.min(arr)

1

In [160]:
np.sin(arr)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111])

In [161]:
np.cos(arr)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219,
        0.96017029,  0.75390225, -0.14550003, -0.91113026, -0.83907153])

In [162]:
np.tan(arr)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128, -3.38051501,
       -0.29100619,  0.87144798, -6.79971146, -0.45231566,  0.64836083])

In [163]:
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

In [174]:
arr = np.exp(arr)

In [175]:
arr

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04])

In [181]:
arr.reshape(5,2)

array([[2.71828183e+00, 7.38905610e+00],
       [2.00855369e+01, 5.45981500e+01],
       [1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03],
       [8.10308393e+03, 2.20264658e+04]])

# Exercise


In [183]:
import numpy as np

In [184]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [185]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [186]:
np.ones(10)* 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [188]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [189]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [195]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [196]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [201]:
np.random.randn(0,1)

array([], shape=(0, 1), dtype=float64)

In [205]:
np.random.rand(1)

array([0.08868899])

In [206]:
np.random.randn(25)

array([ 0.63462823, -0.94308969,  1.03563852,  1.52413045, -0.41765812,
       -1.16793827,  0.55973086, -1.58384339, -1.11478829, -0.50955986,
        0.76605981,  0.47214758, -2.5400546 ,  0.18748798, -0.47870351,
        1.4658822 , -0.22271783, -1.49631477, -0.14502201, -0.91260343,
       -1.2785432 , -0.47925482,  0.18246329,  1.53424245, -0.75788199])

In [212]:
np.arange(1,101).reshape(10,10)/100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [214]:
np.linspace(0.01,1,100).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [215]:
np.linspace(0,1,20).reshape(4,5)

array([[0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632],
       [0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421],
       [0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211],
       [0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ]])

In [216]:
mat = np.arange(1,26).reshape(5,5)

In [217]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [226]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [236]:
mat[3,4]

20

In [241]:
mat[:3, 1:2]

array([[ 2],
       [ 7],
       [12]])

In [250]:
mat[4:5, 0:5]

array([[21, 22, 23, 24, 25]])

In [251]:
mat[4,:]

array([21, 22, 23, 24, 25])

In [254]:
mat[-1]

array([21, 22, 23, 24, 25])

In [257]:
mat[3:,0:5]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [258]:
mat[3:5]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [261]:
np.sum(mat)

325

In [263]:
mat.sum()

325

In [264]:
mat.std()

7.211102550927978

In [268]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

# Pandas

## Series

In [269]:
import numpy as np

In [270]:
import pandas as pd

In [271]:
labels = ['a', 'b','c']    #list

In [272]:
my_data = [10,20,30]       #list

In [273]:
arr = np.array(my_data)

In [275]:
d = {'a':10, 'b':20, 'c':30}    #dictionary (a = key, 10 = value)

In [276]:
my_data

[10, 20, 30]

In [277]:
labels

['a', 'b', 'c']

In [278]:
d

{'a': 10, 'b': 20, 'c': 30}

In [280]:
pd.Series(data = my_data)    #shift+tab - to see wide variety of parameters     (command will show index and data)

0    10
1    20
2    30
dtype: int64

In [281]:
pd.Series(data = my_data, index = labels)

a    10
b    20
c    30
dtype: int64

In [282]:
pd.Series(my_data, labels)

a    10
b    20
c    30
dtype: int64

In [284]:
pd.Series(arr, labels)

a    10
b    20
c    30
dtype: int64

In [285]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [286]:
d

{'a': 10, 'b': 20, 'c': 30}

In [287]:
pd.Series(data=labels)

0    a
1    b
2    c
dtype: object

In [288]:
pd.Series(data=[sum,print,len])

0      <built-in function sum>
1    <built-in function print>
2      <built-in function len>
dtype: object

In [291]:
ser1 = pd.Series([1,2,3,4], ['USA', 'Germany', 'USSR', 'Japan'])

In [292]:
ser1

USA        1
Germany    2
USSR       3
Japan      4
dtype: int64

In [296]:
ser2 = pd.Series([1,2,5,4],['USA', 'Germany', 'Italy', 'Japan'])

In [297]:
ser2    # integer

USA        1
Germany    2
Italy      5
Japan      4
dtype: int64

In [298]:
ser1['USA']

1

In [299]:
ser2['Italy']

5

In [300]:
ser3 = pd.Series(data = labels)

In [301]:
ser3     #object means its a string

0    a
1    b
2    c
dtype: object

In [302]:
ser3[0]

'a'

In [303]:
ser1 + ser2   # float to get all the information possible

Germany    4.0
Italy      NaN
Japan      8.0
USA        2.0
USSR       NaN
dtype: float64